### ISSUE TITLE
Incompatibility with WorldGuard 6.x/Spigot 1.8

### ISSUE THREAD

**Issue by Zach443** [BattlePluginsDev/BattleArena#3]
BattleArena is currently not compatible with WorldGuard version 6 and higher. Without WorldGuard, you are unable to create new arenas, as well as a slew of other issues. This is being worked on, and should be fixed soon. 

Edit: Due to some errors in my test server I falsely came to the conclusion that you are unable to create arenas with WorldGuard v6.x. That being said, BattleArena will not enable properly with WG v6.x installed, so either way you are left without functionality.

**Comment by Europia79** [comment]
There's still a small issue where people can run a non-patched WorldGuard v6.0.0-beta. Currently, there's a version test for a WG 'beta' version... But I will be releasing a better fix that checks if WorldGuard is actually WORKING... Not just if it's on the server.

The way I do this is based off the error from the non-patched version:
```
2015-01-11 22:41:24 [Server thread][INFO] [WorldGuard] Enabling WorldGuard v6.0.0-beta-02
2015-01-11 22:41:24 [Server thread][ERROR] Error occurred while enabling WorldGuard v6.0.0-beta-02 (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
	at com.sk89q.worldguard.blacklist.Blacklist.<init>(Blacklist.java:53) ~[?:?]
	at com.sk89q.worldguard.bukkit.BukkitBlacklist.<init>(BukkitBlacklist.java:31) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldConfiguration.loadConfiguration(WorldConfiguration.java:518) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldConfiguration.<init>(WorldConfiguration.java:211) ~[?:?]
	at com.sk89q.worldguard.bukkit.ConfigurationManager.get(ConfigurationManager.java:235) ~[?:?]
	at com.sk89q.worldguard.bukkit.ConfigurationManager.load(ConfigurationManager.java:202) ~[?:?]
	at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onEnable(WorldGuardPlugin.java:200) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot180.jar:git-Spigot-"606148f"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:333) [spigot180.jar:git-Spigot-"606148f"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot180.jar:git-Spigot-"606148f"]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:352) [spigot180.jar:git-Spigot-"606148f"]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [spigot180.jar:git-Spigot-"606148f"]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:400) [spigot180.jar:git-Spigot-"606148f"]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:368) [spigot180.jar:git-Spigot-"606148f"]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:323) [spigot180.jar:git-Spigot-"606148f"]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot180.jar:git-Spigot-"606148f"]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:496) [spigot180.jar:git-Spigot-"606148f"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_11]
```

As you can see, it goes thru WorldGuardPlugin::onEnable() line 200... Therefore, the Exception interrupts onEnable() and not all the WorldGuard fields gets initialized. When you look at the source code for fields after line 200... You'll see that flagStateManager does not get initialized.

So Zach, the only question we have: When we preform our check on WorldGuard, do we wanna check ALL fields ? Or only flagStateManager field ? What do you think ?

On the one hand, if we check ALL fields indiscriminately of NAME... then I believe we are 'future-proofing' our code for possible WorldGuard changes in the future. Whereas, if we only check the one field that know for certain would break WorldGuard (if null), then we will be in a bad position if sk89q decides to refactor.

Here's a printout of the check so far:
```
2015-01-11 22:41:24 [Server thread][INFO] WGP field: log
2015-01-11 22:41:24 [Server thread][INFO]  is not null
2015-01-11 22:41:24 [Server thread][INFO] WGP field: inst
2015-01-11 22:41:24 [Server thread][INFO]  is not null
2015-01-11 22:41:24 [Server thread][INFO] WGP field: commands
2015-01-11 22:41:24 [Server thread][INFO]  is not null
2015-01-11 22:41:24 [Server thread][INFO] WGP field: configuration
2015-01-11 22:41:24 [Server thread][INFO]  is not null
2015-01-11 22:41:24 [Server thread][INFO] WGP field: regionContainer
2015-01-11 22:41:24 [Server thread][INFO]  is not null
2015-01-11 22:41:24 [Server thread][INFO] WGP field: globalRegionManager
2015-01-11 22:41:24 [Server thread][INFO]  is not null
2015-01-11 22:41:24 [Server thread][INFO] WGP field: flagStateManager
2015-01-11 22:41:24 [Server thread][INFO]  is null
2015-01-11 22:41:24 [Server thread][INFO] WG/WE not present, not compatible, or not supported.
```
I wrote the code a while ago... Haven't released it because I was unsure if I should check all fields, or only  the flagStateManager field. Right now, the check doesn't know any field names: It just gets all the fields and checks each one for null.
